### ISSUE TITLE
Wont initiate

### ISSUE THREAD

**Issue by Pliind** [mykle1/MMM-LICE#1]
{
    module: 'MMM-LICE',
    position: 'bottom_center',                   // Best in left, center, or right regions
    config: { 
		accessKey: "KEY", // Free account & API Access Key at currencylayer.com
		source: "SEK",       // The source currency
		x1: "USD",
		x2: "EUR",
		x3: "GBP",
		x4: "DKK",
		useHeader: false,                 
		header: "Show me the money",
		maxWidth: "400px",
    }
},

This Leaves me with this on my magicmirror:
Source Currency = USD
USD = undefined
EUR = undefined
GBP = unfefined
DKK = undefined

**Comment by mykle1** [comment]
I will take a look at  it after dinner tonight.

**Comment by mykle1** [comment]
First, using the free API Key tells me this ""info":"Access Restricted - Your current Subscription Plan does not support Source Currency Switching." So, that's number 1 issue. If you use the free API plan then you only get to choose one source currency. Mine is set to USD as source and can ONLY be set to USD because I use the free plan. Issue number 2: You must only use supported currencies. The full list is here in json format. http://apilayer.net/api/list?access_key=YOUR-API-KEY&prettyprint=1

**Comment by Pliind** [comment]
Aw that's too bad :( cant pay 10 usd just to have a screen show currency. Thank you for the module, hope you one day solve an international one for the rest of us :)

**Comment by lacalos** [comment]
hi.. this module not working. please see this module
